[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "531eef7bee73ac26d766ed6563d2afe1b89459c5"
os = "macos"

    [[Hwloc.download]]
    sha256 = "7ab2471069d18c95eb2bb965c4869c70ea7b6288541b054e99dd7beca1a8b90d"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.aarch64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "6ba45b95b3aa0468e373e8b4110bb4696e5a51f3"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "28f5c19d8c378d2df35dd813d29ef5ce30b436b159243c3323a06ebfba9d97a7"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.aarch64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "cc0c04c893f7aacad158d22be524d494bd7ec5c7"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "620d09de8dd2c505ac4da25fa03803b49c384f49743ccf4528bbaa38bf10f971"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.aarch64-linux-musl.tar.gz"
[[Hwloc]]
arch = "aarch64"
git-tree-sha1 = "b336e2356b81b59ca97419011fba91d380ce1628"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "641d3f12e5b50ab539a2f86591f07bd7d8dc09d89adefa0e75bf07717abdc4cd"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.aarch64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0cbbf2dff818de4506ab40c2385ac9e74b9df01"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "1922e4018577c8f379c257b2ba754d34cac78b1f68b5bef2d4b215924d2cb484"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.armv6l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6b3dd3762ec33f2c29c469ad92b3cd95037196df"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "ba4cd2f04dbdf6cc52fc3dc6e51212e6a632453d9e9a9c4deee2608faed945de"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.armv6l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ec7d15fd5ad88fb9b03deedb678779b4420ccd4b"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "78bb3e42ef1dfd4afc3e1a77149ee5f3efdfb7203d8d2bb8b65acfc76140117b"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.armv7l-linux-gnueabihf.tar.gz"
[[Hwloc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4d3e29722962ba9ab65b9699b270f4c8294b4c52"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "656692303e9bfe3d2b9ea1acfa2bef718eea62354adceffe1af35b397a4200f6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.armv7l-linux-musleabihf.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "d25a272e52fde12ee09d8791881a7f5f39ce5858"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "d910138c03bf8eb79dec324b64831e136962ef08c36daeda753f8b5e3635a686"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.i686-linux-gnu.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "54ef444e04b77afc4ffa1f9fc36907577865d732"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e6ab8a56e4ab0e9c61c75c4c7c8e850484407951373f0c39b1a81e75a17f1cd6"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.i686-linux-musl.tar.gz"
[[Hwloc]]
arch = "i686"
git-tree-sha1 = "cf89fd49dcd517b11ff15e0b69ae44cc289b6e0a"
os = "windows"

    [[Hwloc.download]]
    sha256 = "9da1b7313a3da9a2ff3ae6835318cde42ebe98853196dc0f303c61edc57e7b16"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.i686-w64-mingw32.tar.gz"
[[Hwloc]]
arch = "powerpc64le"
git-tree-sha1 = "32df0b4c0ebd2f61a8b4aa768b39766767e9f726"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "6525b2439333760a40fb20a851ff7d2c241121132f3808dfb5a4d8b4baf205e0"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.powerpc64le-linux-gnu.tar.gz"
[[Hwloc]]
arch = "riscv64"
git-tree-sha1 = "9c1bfcc6cefe29e0d735773ba72eda2468314b18"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "86c3c503bad45301306e1ca533ab8c59ef65d6d8beb893a84f7230b70209c9fa"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.riscv64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "f26a66a366724d36fe153cb6fb9d0ec1cba60855"
os = "macos"

    [[Hwloc.download]]
    sha256 = "60c4a041bae6251467004cd8a053ee8e94b81ab4cb99d84595ff6c8d71f958fe"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.x86_64-apple-darwin.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "fddb41451df711c595969c8571404433623c75f6"
libc = "glibc"
os = "linux"

    [[Hwloc.download]]
    sha256 = "e3e09e96be9cbc76be319776552e493bba442a9e63cb64eab062e3123230faef"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.x86_64-linux-gnu.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "4d3f1516d0778340bc22800a3de1f4e02bf3cb84"
libc = "musl"
os = "linux"

    [[Hwloc.download]]
    sha256 = "0d3feb7e24518441a76c951a9dc436febfacf3331e386905122708cfc9a06dd8"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.x86_64-linux-musl.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "467d8b51fee1f3e45f2491a6ee98672667185bb2"
os = "freebsd"

    [[Hwloc.download]]
    sha256 = "b685c5534d01d5bc9047304f89092f26dd733b9f61ec0ec02703a140ea244c8f"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.x86_64-unknown-freebsd.tar.gz"
[[Hwloc]]
arch = "x86_64"
git-tree-sha1 = "2f56d121e5fa36bbd4af98be45a4703e03a9f1f8"
os = "windows"

    [[Hwloc.download]]
    sha256 = "060e3fd15c519654c25262f8f63119bedb1ba6c504758d809bcd7676ff058c74"
    url = "https://github.com/JuliaBinaryWrappers/Hwloc_jll.jl/releases/download/Hwloc-v2.12.2+0/Hwloc.v2.12.2.x86_64-w64-mingw32.tar.gz"
