[[Xorg_libpciaccess]]
arch = "aarch64"
git-tree-sha1 = "ba2370d358b07a3ae9ca1892447d8e9f039988dd"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "c50213305acd61c21774c875b3e7d0d910eb50b65ade8f3bc0b53def3eeb10ca"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.aarch64-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "aarch64"
git-tree-sha1 = "93840466ae98ddd3489d89bab6c6803c12114326"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "3f92725be6645097b4eaa2660d2a2eea753f733faab60ee9f730ecfedf21cddc"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.aarch64-linux-musl.tar.gz"
[[Xorg_libpciaccess]]
arch = "aarch64"
git-tree-sha1 = "5c17bec34b4e04bf493e9df4689f09c9805c36a7"
os = "freebsd"

    [[Xorg_libpciaccess.download]]
    sha256 = "a31a3dc32987b92b68f78c537bf393db2f4ea5972bae34c0c1fda5a468860f7e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libpciaccess]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c1538b905261646bfa9a4e02a9bcf8800fd6933"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "5b5bf32986fc4eb7272a6b2b807978c5e6e36dad63b0dd981cea3a124715ebb9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libpciaccess]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db85dc60c33adc76d638afdbedacb39df959e923"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "9e549daec2bdf7fa12fb38438a2270759a98bd7f8e582d57f731cc9309e0408b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libpciaccess]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bf4b4960148f882322346be4e6be9201c3f2a142"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "5a5e63fdb1438268c3f94df415d830c9f8c86e66c82063ffe878c9e3e31decaa"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libpciaccess]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a3aba646d4afdd7afa0a71928c3f998574224e96"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "de13a108ce6225d59f59e212a8373ad8961ff38fa413f216baf3127f3b996388"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libpciaccess]]
arch = "i686"
git-tree-sha1 = "9768405e9a8ab6803fb63d6f1fb3420298b5e2e0"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "b236b28945fbfc3e18865b4f09fd19196b2ab02a6ee15e149ce4f5cbff51dafd"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.i686-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "i686"
git-tree-sha1 = "20276716a00a8892534fdab1353a7d70c5d98fd6"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "ba272d065989e1a053ee82d0ed3aa6b21257cdb629c90b59e0cf1eb978b9f197"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.i686-linux-musl.tar.gz"
[[Xorg_libpciaccess]]
arch = "powerpc64le"
git-tree-sha1 = "be41d6a941e15d5298290168d2146eca8b68c2b9"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "8c58253c6037430ff59c6ea0676a1a5fe2f1d8b827d31c8e152214fcc5418ff5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "riscv64"
git-tree-sha1 = "cf234385e998b1d2371df82e5af3687a0f5bd1f2"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "316bed4399e8849ffba07e1a623d9f70c6d8e4c1abc9662d1a84f974903cf255"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.riscv64-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "x86_64"
git-tree-sha1 = "02f7ccbf4bbe00dcdd34eba3f36cd5e8f76f1769"
libc = "glibc"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "a4933cd49f249e001d85dee6655d8c514597b0ebddfb381c7d5fd381ce119b5c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.x86_64-linux-gnu.tar.gz"
[[Xorg_libpciaccess]]
arch = "x86_64"
git-tree-sha1 = "b6614f01be0e013d464e274f35c2659a5d404bb3"
libc = "musl"
os = "linux"

    [[Xorg_libpciaccess.download]]
    sha256 = "802d3fd1a643402551abf91d39da5c3fbeb0c74473dd7701c04ce58d5c98e508"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.x86_64-linux-musl.tar.gz"
[[Xorg_libpciaccess]]
arch = "x86_64"
git-tree-sha1 = "0501c4367ab008bcd235daa16f3cb8938bc6f7e2"
os = "freebsd"

    [[Xorg_libpciaccess.download]]
    sha256 = "00c59917f661216132cfab191cd460df0f5d7f2aba561a550dae2e84dd362397"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libpciaccess_jll.jl/releases/download/Xorg_libpciaccess-v0.18.1+0/Xorg_libpciaccess.v0.18.1.x86_64-unknown-freebsd.tar.gz"
